### ISSUE TITLE
Is there an online example/demo ?

### ISSUE THREAD

**Issue by finscn** [pixijs/pixi-projection#1]

**Comment by ivanpopelyshev** [comment]
Still working on implementation :) I'm doing 2d projections first. Its a very strange thing.

**Comment by djmisterjon** [comment]
+1 for aa little demo

**Comment by ivanpopelyshev** [comment]
http://pixijs.github.io/examples/#/projection/basic.js

http://pixijs.github.io/examples/#/projection/quad.js

Work in progress.

**Comment by ivanpopelyshev** [comment]
@finscn feel free to help me with that thing. You're one of few people who know how to make projections in pixi!

**Comment by finscn** [comment]
@ivanpopelyshev , I don't know which algorithm you used. but it's different from mine.

Is there some documents about the algorithm you used ?

**Comment by ivanpopelyshev** [comment]
No, its straight from my head. 

1. Matrix is indexed by columns (0,1,2) if first column.
2. first column is a vector to X projection point (x1,y1,1), normalized by distance so we have no scale, (x1/d, y1/d, 1/d);
3. second column is for Y.
4. setAxisX(x,y,1) adds projection point X
5. setAxisX(x,y,0) sets a direction for X (just a rotation)
