### ISSUE TITLE
projected pixi-spine?

### ISSUE THREAD

**Issue by kimsyv** [pixijs/pixi-projection#10]
Would it be possible to add functionality to convert a pixi-spine object to 2d? I can get the proper projection of a spine object using RenderTexture but that is not as performant and stable as using the spine object directly on stage.

What I mean is like:

```
var spineObject = new PIXI.spine.Spine(data);
spineObject.convertTo2d();
```

By doing the above the spine would then follow the projection of the Container2d or Sprite2d it is added as a child to.

**Comment by ivanpopelyshev** [comment]
### Sprite

There's convertSubtreeTo2d , but make sure all sprites were created, run "spine.upate(0)". It might be a problem if some of attachments are hidden.

One more way:

```js
PIXI.spine.SpineSprite.prototype = new PIXI.projection.Sprite2d();
PIXI.spine.SpineSprite.constructor = function(tex) {
   PIXI.projection.Sprite2d.call(this, tex);
}
```

And even that might work, https://github.com/pixijs/pixi-spine/blob/master/src/Spine.ts#L447, override that way it creates Sprite2d and not SpineSprite

```js
PIXI.spine.Spine.prototype.createSprite = function() { ... }
```

### Meshes

projection doesnt support meshes. If you use meshes, I can add them :)

**Comment by kimsyv** [comment]
Okay. I will try these out. Will report how it goes :)

Thanks!

**Comment by kimsyv** [comment]
I can't get the spine object to be projected. If I use the convertSubtreeTo2d on the spine object I get this error:

```
compilation.ts:2515 Uncaught TypeError: Cannot read property 'length' of undefined
    at Sprite2dRenderer.fillVertices (compilation.ts:2515)
    at Sprite2dRenderer.MultiTextureSpriteRenderer.flush (compilation.ts:405)
    at Sprite2dRenderer.MultiTextureSpriteRenderer.stop (compilation.ts:489)
    at WebGLRenderer.setObjectRenderer (WebGLRenderer.js:345)
    at Container2d._renderWebGL (Sprite.js:304)
    at Container2d.renderWebGL (Container.js:409)
    at Spine.renderWebGL (Container.js:414)
    at SpineContainer2d.renderWebGL (Container.js:414)
    at Sprite2d.renderWebGL (Container.js:414)
    at Symbols.renderAdvancedWebGL (Container.js:467)
```

And if I set the PIXI.spine.SpineSprite to extend PIXI.projection.Sprite2d instead of  PIXI.Sprite it does not affect anything. I also changed all references to PIXI.Container to instead reference PIXI.projection.Container2d in pixi-spine, but that does not help either.

![spine_rendertexture](https://user-images.githubusercontent.com/31270432/30962736-9ff97e66-a453-11e7-8fd4-cc7151567319.png)

This is how it should look. I get this by rendering the spine object into the RenderTexture of a Sprite2d. And then I use another Sprite2d as container.

![spine_direct](https://user-images.githubusercontent.com/31270432/30962779-c93bb7da-a453-11e7-8a56-bcac6fba77f0.png)

This is how it looks when I add a pixi-spine object directly into the Sprite2d container. And this looks the same with unaltered pixi-spine as it does with "hacked" pixi-spine.

_In both the above examples I have the alpha of the spine as 0.3, so you can see the boundaries of the Sprite2d container (which has a white 0.5 alpha texture)_

**Comment by ivanpopelyshev** [comment]
Thank you! Now I have to investigate this personally :)

**Comment by ivanpopelyshev** [comment]
Are there any meshes in your spine object?

**Comment by ivanpopelyshev** [comment]
OK, I've made it that way it works on meshes. Please download latest versions and try it with first approach - 
```
spineObj.convertTo2d();
```

**Comment by kimsyv** [comment]
I tried it now. It is better, but it does not deform properly.

![spine_direct_2](https://user-images.githubusercontent.com/31270432/31002915-cb739bd8-a4f5-11e7-8f25-8635aeeac590.png)
![spine_direct_2_1](https://user-images.githubusercontent.com/31270432/31003829-5e782d5a-a4fa-11e7-9744-c81ff5b3520c.png)
![spine_direct_2_2](https://user-images.githubusercontent.com/31270432/31003832-61145a7a-a4fa-11e7-97eb-90fc80061cae.png)

As a rectangle or parallelogram it seems fine, but when I do a trapezoid or just irregular it does not deform right.
Is that perhaps due to my spine file? Or do I need to override more in the pixi-spine regarding meshes?

**Comment by ivanpopelyshev** [comment]
The projection plugin is a very big hack. Now I really have to test it on my spine files :)

**Comment by kimsyv** [comment]
Any progress on this one?

**Comment by ivanpopelyshev** [comment]
Try latest pixi-spine (1.5.8) with latest pixi-projection-spine.js: 

```js
var spineObj = new PIXI.projection.Spine2d(spineData);
```

**Comment by kimsyv** [comment]
Awesome! I don’t have time to try this out until monday but I’ll try this first thing then :)

**Comment by kimsyv** [comment]
This now works as expected! :) The spine is projected correctly.
