### ISSUE TITLE
Could it work with TilingSprite ?

### ISSUE THREAD

**Issue by arthurmuchir** [pixijs/pixi-projection#12]
Hi,
I have been trying to make projection works with TilingSprite without success.
TilingSprite extending Sprite, I think there must be an easy way to do it.

Thanks for any help

**Comment by ivanpopelyshev** [comment]
Look at https://github.com/pixijs/pixi-projection/tree/master/src/proj2d/mesh.

If you are ready to change the lib, add the same for TilingSprite and it'll work. 

I can do that fast, but I have so many issues to work on right now. Please explain why do you need it.

**Comment by arthurmuchir** [comment]
Thanks for your fast answer,
I will look at it, I do not get the relation between Mesh and Sprite for now.

I need it to produce the effect of an infinite floor moving (I then only have to increase tilePosition.y)

![floor](https://user-images.githubusercontent.com/6191766/35035032-5507b8d6-fb70-11e7-8b6f-92606ce09f59.jpg)

**Comment by ivanpopelyshev** [comment]
Its not easy, I'm working on it. I need to modify renderer, and then it'll work: https://github.com/pixijs/pixi-projection/tree/master/src/proj2d/tiling

**Comment by arthurmuchir** [comment]
Thanks a lot for taking time on it. Don't want to disturb.

**Comment by ivanpopelyshev** [comment]
I've tried that but now i see some problems, cant reproduce what you want yet. TilePosition moves are wrong, I'm investigating that.

**Comment by ivanpopelyshev** [comment]
Done: http://pixijs.io/examples/#/projection/plane-tiling.js 

I switched the order of projection and local transformations, so you can specify axisY related to tilingSprite position, not to its internal offset. Transformations are not obviuous at all, but at least it works.

Update to latest 0.1.9

**Comment by endel** [comment]
Hey there. Is this stable across WebGL / Canvas? Kudos on this library, awesome work.

**Comment by ivanpopelyshev** [comment]
Its webgl-only. 2d context has only 3x2 matrices and they're not enough for that kind of transformations.
