### ISSUE TITLE
rmmv ? and map project camera

### ISSUE THREAD

**Issue by djmisterjon** [pixijs/pixi-projection#14]
I would like to know if it is possible to easily integrate this module in the Third party runtimes of RMMV?
Knowing that I do not use the basic software core for rendering (tiles and charset).

I work on my side on a small plugin that offers a publisher more suitable for projects a bit less pixel Art and 2D.
The idea is to realize a small complex editor worthy of UNITY which makes it possible to manage the different altas, layers available for a classic and functional Workflow.
So logically, if am not wrong in my workFlow, we have.
**Sprites**: single large pictures textures, without frames
**TilesSheets**: Multiples small pictures with frames (texturePacker)
**SpriteSheets**: Sequential animations + FX from After Effect or other.. (texturePacker)
**SpineSheets**: Multiples Small pictures textures but arrange. (spine2D)

Originally, rmmv does not take spriteMap, but I hack to allow the map to be a simple single large sprite.
what would be the approach to integrate a simple effect, without much complexity, 2.5D immersion for the map and sprites
Do existe a tutorial and a good demo with the rmmv core scene?

Let see how my workflow look for now.
This its how i understand pixi.
[![youtube](https://i.ytimg.com/vi/I_Evrh12yOM/2.jpg?time=1520922041242)](https://youtu.be/I_Evrh12yOM)

thanks

**Comment by ivanpopelyshev** [comment]
I dont understand what do you want with it.

Its either about pixi-projection and upcoming 3d in it,  either about pixi-heaven: https://gameofbombs.github.io/examples-heaven/#/mesh/animation.js
