### ISSUE TITLE
spine support?

### ISSUE THREAD

**Issue by macguffin** [pixijs/pixi-projection#15]
Hi Ivan the source suggests that this will work with Spine. Can you convert an existing spine element to work in the same way you can with a Sprite or Container?

Thanks

**Comment by ivanpopelyshev** [comment]
You have to take `pixi-projection-spine.js` , and use `PIXI.projection.Spine2d` instead of normal spine instance. Or you can make conversion procedure yourself based on this thing: https://github.com/pixijs/pixi-projection/blob/master/spine/Spine2d.ts
