### ISSUE TITLE
Uncaught TypeError "attachShader" when loading pixi-projection on older device

### ISSUE THREAD

**Issue by macguffin** [pixijs/pixi-projection#16]
Hi Ivan, I was testing this pixi-projection stuff on an older Samsung device and got this error (this is from your basic example page)

<img width="914" alt="pixiprojection" src="https://user-images.githubusercontent.com/567652/37396053-b678e542-276f-11e8-8e89-644b8a160734.png">

The device does run the rest of the PIXI webGL stuff and is running in webGL mode on the renderer.
This error happens when the pixi-projection.js file is loaded, even without any other pixi-projection code.

As the projection stuff is only webGL compatible I was going to have a none projected canvas fallback anyway. Is there anything I could test the webGL instance for to see if the device can handle the pixi-projection code?

Thanks in advance for your help.

**Comment by ivanpopelyshev** [comment]
There should be more errors there.

**Comment by macguffin** [comment]
wow that was fast, thanks.

ahh just seen ERROR: 0:1 'highp' :precision is not supported 

Can I test for this on the webGL renerer?
👍

**Comment by ivanpopelyshev** [comment]
`precision highp float;` is hard-coded in pixi-projection. You can remove it and may be it'll work. If it doesnt, try `PIXI.settings.PRECISION_VERTEX = PRECISION.PRECISION.MEDIUM`

**Comment by macguffin** [comment]
thanks so much for the pointers.

really appreciate it

**Comment by macguffin** [comment]
just as a follow up removing highp float from the shaderVert has got rid of the error
