### ISSUE TITLE
 strange behavior  free transform bug ?

### ISSUE THREAD

**Issue by djmisterjon** [pixijs/pixi-projection#2]
I noticed this strange behavior in free transform

![GitHub Logo](https://i.imgbox.com/eGBpz1o2.gif)

**Comment by ivanpopelyshev** [comment]
Yes,  I know :) Its very unstable function, I dont know how to fix it yet.

**Comment by djmisterjon** [comment]
I do not know if this can help you, but there is a functional example here.
The problem is that it is an applet from Geogebra .
So no javascript to help more, only mathematical formula.

Applet: Linear transformation in two dimensions
http://mathinsight.org/applet/linear_transformation_2d

**Comment by ivanpopelyshev** [comment]
They describe simple affine transform that pixi has :(

Nothing about "map square to random quad".

**Comment by finscn** [comment]
There is a sample of perspective   at  http://evanw.github.io/glfx.js/demo/ 

I hope it could help you.

My perspective renderer uses the method like it.

**Comment by ivanpopelyshev** [comment]
Found much easier formulas: http://reedbeta.com/blog/quadrilateral-interpolation-part-1/

Fixed.
