### ISSUE TITLE
About Quad bilinear.

### ISSUE THREAD

**Issue by finscn** [pixijs/pixi-projection#3]
sometimes the result is A , sometimes it's B.
A
<img width="406" alt="2017-08-03 11 56 46" src="https://user-images.githubusercontent.com/288367/28931104-a0f9b78a-783a-11e7-9211-c701a6eb8edf.png">

B
<img width="392" alt="2017-08-03 11 56 54" src="https://user-images.githubusercontent.com/288367/28931106-a28cc2a4-783a-11e7-80a2-8e14ba6be227.png">

Why? And How to estimate the result ?

**Comment by ivanpopelyshev** [comment]
Order of points. I'll make it better and write an explanation :)
