### ISSUE TITLE
About Quad projective.

### ISSUE THREAD

**Issue by finscn** [pixijs/pixi-projection#4]
<img width="362" alt="2017-08-03 11 59 35" src="https://user-images.githubusercontent.com/288367/28931199-eac9776a-783a-11e7-9287-9b69b61808f8.png">

 the right-bottom point is not fixed at the right-bottom red rect. Why ?

And When use the normal method with matrix 4*4 , the result is not as same as the method in http://reedbeta.com/blog/quadrilateral-interpolation-part-1/

**Comment by ivanpopelyshev** [comment]
Because you made one of points inside the triangle of others. So I fix three points, and if fourth is bad i either ignore it, either show something close.

**Comment by djmisterjon** [comment]
i also nitice this issu !
![GitHub Logo](https://i.imgbox.com/Y0tPp4jA.gif)
@ivanpopelyshev  thank for your awsome work !

**Comment by ivanpopelyshev** [comment]
That's not an issue. That's my policy in case shit happens: "three point must stay, fourth can go".

**Comment by djmisterjon** [comment]
I am not at this stage of programming.
But I will like to integrate your plugin with my introduction.
I use the core of rmmv, with you a tutorial for integration.


Ideally I would like to add a **EventListener**  
Which according to the position of the mouse, the background will make a projection .

I never have trying have integrating modules into rmmv, but if you have good tutorial?.
Sample of my game engine  now , 
https://www.youtube.com/watch?v=7-DUC_uMIbs

**Comment by ivanpopelyshev** [comment]
Ask @Dairnon

**Comment by Dairnon** [comment]
If your trying to add a module into MV, easiest way is to just add it to the index.html in your projects main directory (where the Game.rpgproject is) 

You'll notice inside the index.html there are script tags

`<script type="text/javascript" src="js/libs/pixi.js"></script>
`

An example of me integrating pixi-ui and pixi-layers. 
![uxnekaw](https://user-images.githubusercontent.com/17523069/28993022-8d37df52-7960-11e7-941a-5efc9e947b35.png)


All you have to do is add another that links you to pixi projection. 


So you'd add something like 
`<script type="text/javascript" src="js/libs/pixi-projection.js"></script>`
And then add pixi-projection into your js/lib folder.

**Comment by djmisterjon** [comment]
@Dairnon 
thank is so very simples.
It was not that simple with PIXIMULTISTYLES, I had to create a new full-fledged source code of over 600 lines.
Delighted that the integration of this module is so simple and easy !

**Comment by finscn** [comment]
Where could I find the source of pixi-layers ?

**Comment by ivanpopelyshev** [comment]
https://github.com/pixijs/pixi-display/tree/layers

**Comment by ivanpopelyshev** [comment]
yes

**Comment by Dairnon** [comment]
@djmisterjon I see why you had to re-write it, it was written in typescript. I would like to point out tho that instead of needing to re-write the entire thing, you could have compiled it into regular javascript, then imported that the normal way. (I think you made it harder for yourself xD) 

Tho looking at the examples for it, it seems the developer already has a compiled version which would work (but it doesn't appear to be publicly showing in github for some reason)

You could just download the project, run npm on the folder via console, then run npm -i, then run the build script for it.

Something like npm build

**Comment by djmisterjon** [comment]
@Dairnon yes i was try to convert it
https://www.typescriptlang.org/play/
However the performance was not at the rendezvous, the code was rather poorly optimized.
So I as simply rewrite new code with my performance requirement.
