### ISSUE TITLE
strange distortion from bottom when navigate on fake z axis.

### ISSUE THREAD

**Issue by djmisterjon** [pixijs/pixi-projection#43]
i get strange distortion from bottom when i try to navigate in deep `fake z`.

![proj distortion](https://user-images.githubusercontent.com/24865815/58755977-de4fca80-84bc-11e9-81a9-4754dfb27037.gif)
Any tips or suggest to fix this or avoid this ?

**Comment by ivanpopelyshev** [comment]
I don't see distortion on that gif

**Comment by djmisterjon** [comment]
am trying to made you a demo for you can see.
unfortunately, I have a problem I missed code somewhere.
I have to leave for the day but I will come back to my office tonight, I will try make it work.
https://www.pixiplayground.com/#/edit/wfbC9XyA1dSPvFlZZ9YLp

btw it could be a nice demo to show another aspect of your projections :)

**Comment by djmisterjon** [comment]
@ivanpopelyshev  yhea it work :)
here the strange behavior i talked about.
https://www.pixiplayground.com/#/edit/kYDSy6se1qOymLsld~1wg
can you try move the **z**
![image](https://user-images.githubusercontent.com/24865815/58768499-3db7e400-856a-11e9-8da8-ef650102ae9f.png)
You will see a strange fish eye distortion from bottom.
It this normal ? a easy alternative ?

I have the impression that everything stretches when i want move in z axis.
