### ISSUE TITLE
return matrix crash

### ISSUE THREAD

**Issue by djmisterjon** [pixijs/pixi-projection#44]
i think you forget return matrix here ?
https://github.com/pixijs/pixi-projection/blob/63a7dd7ec31184557604ede3b9b4c3be90bfbdfe/src/proj3d/Matrix3d.ts#L412

![image](https://user-images.githubusercontent.com/24865815/59387781-04d0f980-8d38-11e9-96f1-9fe6d949af99.png)

**Comment by ivanpopelyshev** [comment]
yeah, certainly. ill fix it tomorrow )
