### ISSUE TITLE
PIXI.BatchShaderGenerator is not a constructor

### ISSUE THREAD

**Issue by king514jy** [pixijs/pixi-projection#48]
1：
![image](https://user-images.githubusercontent.com/5669543/60073705-b66a2480-9753-11e9-9bc9-d5e7d4aed100.png)
`<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style>* {padding: 0; margin: 0}</style>
</head>
<body>
    <script type="text/javascript" src="https://pixijs.download/v5.0.4/pixi.js"></script>
    <script type="text/javascript" src="libs/pixi-projection.js"></script>
    <script type="text/javascript" src="quad-homo.js"></script>
</body>
</html>`
Pixi-projection.js and quad-homo.js are the latest files downloaded

2：
Use pixi-legacy to run
![image](https://user-images.githubusercontent.com/5669543/60073888-37292080-9754-11e9-8df2-41feb574c7b9.png)
![image](https://user-images.githubusercontent.com/5669543/60073919-49a35a00-9754-11e9-9e4a-6def452e53f2.png)

`<body>
    <script type="text/javascript" src="libs/pixi-legacy.min.js"></script>
    <script type="text/javascript" src="libs/pixi-projection.js"></script>
    <script type="text/javascript" src="quad-homo.js"></script>
</body>`
Did not achieve the effect in the example

**Comment by ivanpopelyshev** [comment]
Please use `pixijs.download/dev/pixi-legacy.js` , its dev version. Just 5.0.4 is not enough.

**Comment by king514jy** [comment]
> Please use `pixijs.download/dev/pixi-legacy.js` , its dev version. Just 5.0.4 is not enough.

thinks

**Comment by ivanpopelyshev** [comment]
We hope to release 5.1.0 soon, it'll have `BatchShaderGenerator` in it ;)
