### ISSUE TITLE
draw graphic line between two 3d objs?

### ISSUE THREAD

**Issue by djmisterjon** [pixijs/pixi-projection#51]
Hey ivan, or other people use this, what formula to compute and draw distance between 2 container3d?
I was success with projection 2d to find a formula that worked.
it was little complicated.
```js
               Object.keys(c.pathConnexion).forEach(id => { // connextion id to sprite ID
                   const cc = $objs.cases_s[id]; // dataobj conected
                   let point = new PIXI.Point(0,0);
                   const xy   = $camera.toLocal(c, $stage.scene, void 0, void 0, PIXI.projection.TRANSFORM_STEP.BEFORE_PROJ);//dataObj  .sprite.toGlobal(point)
                   const xy_c = $camera.toLocal(cc, $stage.scene, void 0, void 0, PIXI.projection.TRANSFORM_STEP.BEFORE_PROJ); //dataObj_c.sprite.toGlobal(point)
                   const dX = (xy_c.x-xy.x)*$camera._zoom;
                   const dY = (xy_c.y-xy.y)*$camera._zoom;
                   const path = new PIXI.Graphics();
                   path.lineStyle(4, 0x4286f4, 1);
                   path.moveTo(0,0).lineTo(dX, dY).endFill();
                   const scaleXY = new PIXI.Point(~~1/c.scale.x/$camera._zoom,~~1/c.scale.y/$camera._zoom);
                   path.scale.copy(scaleXY);
                   c.addChild(path);
                   c.Debug.path.graficConection.push(path);
                   c.Debug.path.addChild(path);
               });
```

But now with 3d projection the system changed, it more easy, but am not able to draw a line connection between 2 objs?
Upper is my target result i want. (photoshoped)
And bottom it the weird result i get.
![afe-a3efga3fg](https://user-images.githubusercontent.com/24865815/61821509-69966e00-ae25-11e9-975f-5c2d435f3df9.jpg)

Did you have demo example or code to help me?
it's been since an hour i try without success . :(
it's probably too simple?

**Comment by ivanpopelyshev** [comment]
ok, ill look at it soon

**Comment by djmisterjon** [comment]
Did you think this can help, i hack the demo to show where am lost.
https://www.pixiplayground.com/#/edit/7uKKF527mdr7muT5Ly5_R

See `line:94` where we try draw a line from `chara1` to `chara2` 
the code where am stuck are in line `128`.
hope the demo can help ?

**Comment by ivanpopelyshev** [comment]
I did a few experiments, but it turns out my `toLocal` is VERY buggy in 3d space and i cant draw this line.

I'm afraid we need better camera class for that, because we really need partial transform tocompute relative coords (from camera to element).

Maybe in weekend.

**Comment by ivanpopelyshev** [comment]
I think it'll be better if I use `toLocal` and `toGlobal` ONLY for 2d coords, and it'll return coords in XY space of element , that way it'll work everywhere. For 3d relative coords we need other functions.

**Comment by djmisterjon** [comment]
ok i see, thanks for your time and help, i will also try again more experiment with toLocal, and if i found something i will update.

**Comment by ivanpopelyshev** [comment]
Dont try it until i fix it, please. I dont want you to lose time :)

**Comment by ivanpopelyshev** [comment]
I already know how to fix that.

**Comment by djmisterjon** [comment]
ho ok i see , i will work on other thing :)
i was get more near result by trying convert graphics to sprite3D and play with math.PI and rotation.
But it i don't get it.
https://www.pixiplayground.com/#/edit/7uKKF527mdr7muT5Ly5_R
I will give another try this week , thanks you so much.

**Comment by djmisterjon** [comment]
@ivanpopelyshev 
I can not stop myself from trying lol.
i think i succeed without `localBounds`.
it might be interesting to add this method to your plugin, maybe in the static class as a tool ?
`PIXI.projection.utils.getDistanceFrom(fromLocal,toGlobal);`

what do you think ?  `line:145:151`
https://www.pixiplayground.com/#/edit/hN_1Nmxu9fF5Jpmp_2mtC
i add a live update if you try also move the `CRARA`.
the only issue i can see is it does not work if the sprites are not the same height `y`.
