### ISSUE TITLE
culling

### ISSUE THREAD

**Issue by djmisterjon** [pixijs/pixi-projection#52]
i have some difficulty with culling in projection.
Am no able to proceed with .getBounds(), because i get weird math values thats i not understand !.
So i experimente like this, it work but am really not sure if is the best ways, i will probably get issue because it no compute bounds correctly.
```js
    /**@description update from updateMain in sceneManager */
    update(){
        this.view.scale3d.set(this._zoom);
        this.view.euler.y = this._ang;
        this.view.euler.x = this._perspective;
        if(this._angleToFocus){
            //this.view.setPlanes(this._focus+Math.abs(this._ang*2000), this._near, this._far, this._orthographic)
        }
        if( this._culling ){
            const b = {left:(this.view.position3d._x-$app.screen.width/2)*this._zoom,right:(this.view.position3d._x+$app.screen.width / 2)*this._zoom}
            for (let i=1,list = $stage.scene.children, l=list.length; i<l; i++) {
                const c = list[i];
                if(c.position3d){
                    const inside = c.position3d._x>b.left && c.position3d._x<b.right;
                    c.renderable = inside;
                }
            };
        }
    };
```
![culling](https://user-images.githubusercontent.com/24865815/62007332-4405af00-b11a-11e9-8ae5-748f3f3a5097.gif)

Any tips or demo to show how proceed in pixi projection with culling ?
I need this because despite my optimization., with a lot of stuff, i start get poor performance.

**Comment by ivanpopelyshev** [comment]
next week. I dont have time right now.

**Comment by ivanpopelyshev** [comment]
You are the one who's pushing this plugin :) I'm happy to help because then i will be able to promote it to other people o/

**Comment by djmisterjon** [comment]
yes your plugin has a lot of potential and very simple uses.

btw did you think get bound not work properly ?
because it seems to me that i have tested this with pixiProjection 2d and was able get  cooerente values, but with proj3d , my Camera system is a bit different because i do not use the pivot but the position3d on the camera, and i wonder if that do not false the values.

Did you think if a made you a playground this will help you ?

**Comment by djmisterjon** [comment]
this is the demo where am stuck
when you will have time :)
line:`237`  you can also disable culling with check box
https://www.pixiplayground.com/#/edit/wI3E4~RHjM8bMFtDOc3On

**Comment by djmisterjon** [comment]
thanks @Dairnon :):) i think this is fine.
https://www.pixiplayground.com/#/edit/r_I7fSMxL9Uyu6ZuL5u6x
