### ISSUE TITLE
Why `2D Quad bilinear` can't run with PIXI v5 ?

### ISSUE THREAD

**Issue by finscn** [pixijs/pixi-projection#57]
I found this feature is disabled in https://pixijs.io/examples/#/plugin-projection/quad-bi.js.

When will it be ready ?  or never be supported in Pixi v5 ?

**Comment by ivanpopelyshev** [comment]
I didnt port it yet. We have no support for custom batching uniforms :(

**Comment by ivanpopelyshev** [comment]
It works.

**Comment by bigtimebuddy** [comment]
Good work Ivan, closing.
