### ISSUE TITLE
Unable to setup pixi-projection on ReactJS project

### ISSUE THREAD

**Issue by freglyc** [pixijs/pixi-projection#66]
I am currently attempting to import pixi-projection within a React project and am receiving the following error:
```
Attempted import error: 'projection' is not exported from 'pixi.js' (imported as 'PIXI').
```

I am importing pixi-projection the following way:
```
import * as PIXI from "pixi.js";
import 'pixi-projection'
```

I have also tried to import what you see below with no luck:
```
import * as PIXI from "pixi.js";
global.PIXI = PIXI;
require("pixi-projection");
```

**Comment by ivanpopelyshev** [comment]
```
import * as PIXI from "pixi.js";
global.PIXI = PIXI;
require("pixi-projection");
```

try `window.PIXI`

**Comment by ivanpopelyshev** [comment]
Also make sure that import is executed after that first module.

**Comment by freglyc** [comment]
Using window.PIXI does the trick! As a side note, you do have to access the module through window.PIXI.projection instead of PIXI.projection with this approach.

**Comment by ivanpopelyshev** [comment]
There's access from `PIXI.projeciton` if you dont try to use `import {projection} from 'pixi.js'` and use * import instead

**Comment by freglyc** [comment]
There appears to be an issue with accessing PIXI.projection in this manner. 

```
import * as PIXI from "pixi.js";
window.PIXI = PIXI;
require("pixi-projection");
```

window.PIXI and PIXI appear to be separate object instances so attempting to access the projections plugin with PIXI instead of window.PIXI results in the initial error mentioned at the start of this thread. I was able to remedy this by using the following:

```
import * as PIXI from "pixi.js";
window.PIXI = PIXI;
require("pixi-projection");
export default PIXI;
```

I effectively imported everything to a central location and now export my definition of PIXI into all necessary files.

**Comment by ivanpopelyshev** [comment]
OH, That's a great idea! Thank you, I will recommend it to all other users. Especially because that's how i think Pixi+plugins will look in future - you just bundle all the plugins you need in single file, tree-shaking can handle that.

**Comment by adilmas13** [comment]
Was facing the exact same issue when trying to access Camera3d. And as mentioned by @freglyc window.PIXI and PIXI are two different instances.  
Thanks for the help
FYI.. Incase anyone is using ReScript/ReasonML and are having a tough time getting a hold of the Camera3d or any other projection object. See the following

1) Add a raw
```
%raw
{|
    window.PIXI = PixiJs;
    require("pixi-projection");
|};
```

2) Write a js file camera.js
```
export function Camera3d(){ 
    return new window.PIXI.projection.Camera3d();
}
```

3) write a module in the same directory as the js file
```
module Camera = {
  type t;
  [@bs.module "./camera.js"] 
  external create: unit => t = "Camera3d";
};
```
