### ISSUE TITLE
How to use PIXI AnimatedSprite in pixi-projection?

### ISSUE THREAD

**Issue by freglyc** [pixijs/pixi-projection#69]
I've been looking around but it is currently unclear if AnimatedSprites are supported or if there is a workaround to utilize them to some extend in conjunction with this plugin. Any help on the subject would be greatly appreciated!

**Comment by ivanpopelyshev** [comment]
**Easy:**

You can use convertion function on AnimatedSprite (to 2d or 3d)

**Medium, but results can be better:**

Also. you can take the approach from pixi-heaven: https://github.com/gameofbombs/pixi-heaven/blob/master/src/animation/AnimationState.ts

Copy that code and make your own AnimationState class.

This is a component that can animate any element with a texture. Just store it somewhere nearby 

```js
let anim = new AnimationState (textures);

anim.bind(mySprite3d);
```

The only bad thing is that it wont unregister when sprite is destroyed, but you can add something like this in `update()`:

```js
if (!this._target.transform || !this._target.parent) {
   // no transform or no parent -target was destroy()  ed
    this.stop();
    return;
}
```

Howevre i didnt patch that class with latest v5 changes, so you might want to actually look in v5 AnimatedSprite sources Look at them anyway - https://github.com/pixijs/pixi.js/blob/dev/packages/sprite-animated/src/AnimatedSprite.ts

Its class that supposed to be a **baseline** for your animation, not just something you use without knowing whats inside. Usually people add more features specific to their game.

**Comment by freglyc** [comment]
Perfect thank you!

**Comment by freglyc** [comment]
It appears that convertTo2d is nonfunctional for Sprites. See issue #71
