### ISSUE TITLE
this.vertexData2d is NULL - Mesh3d2d.ts

### ISSUE THREAD

**Issue by sansfab** [pixijs/pixi-projection#70]
Please insert the fix you made in the "Sprite2d.ts" file row 25 also in the file "Mesh3d2d.ts".
error on "this.vertexData2d.length" row 36.

Thank you

**Comment by ivanpopelyshev** [comment]
oh, interesting

**Comment by ivanpopelyshev** [comment]
OK version 0.3.11 is both here and in npm

**Comment by sansfab** [comment]
thank you!!
