### ISSUE TITLE
convertTo2d() nonfunctional for Sprites

### ISSUE THREAD

**Issue by freglyc** [pixijs/pixi-projection#71]
Utilizing convertTo2d() results in a failure to display the sprite. See below: 

```
let tile = new PIXI.projection.Container2d();
tile.addChild(new PIXI.projection.Sprite2d(Loader.resources.tile.texture));
let outline = new PIXI.Sprite(Loader.resources.outline.texture);
outline.convertTo2d();
tile.addChild(outline);
```

In the above example the outline object is no longer visible with no errors thrown. Utilizing the below code works as intended and displays correctly:

```
let tile = new PIXI.projection.Container2d();
tile.addChild(new PIXI.projection.Sprite2d(Loader.resources.tile.texture));
tile.addChild(new PIXI.projection.Sprite2d(Loader.resources.outline.texture));
```

**Comment by ivanpopelyshev** [comment]
Nope, it works. take the latest version.

**Comment by freglyc** [comment]
Hmm it appears calling convertTo2d is not referencing the desired code. Copying the source code of convertTo2d into my file allows the rendering to work as intended but calling someSprite.convertTo2d() causes issues described above.

**Comment by ivanpopelyshev** [comment]
I need more details. Do you use latest pixi-projection or not?

**Comment by freglyc** [comment]
I believe i am using the latest pixi-projection verison 0.3.11 along with pixi version 5.2.1. I have also removed and reinstalled everything to no avail. My best guess is that it could be an import issue. I am currently importing everything into one file and exporting a centralized pixi reference to all others:

```
import * as PIXI from "pixi.js";
window.PIXI = PIXI;
require("pixi-projection");
export default PIXI;
```

**Comment by ivanpopelyshev** [comment]
Hm , it should work but you say it doesnt.. I'm interested. Can you make minimal example and zip it?

**Comment by freglyc** [comment]
It appears to work as intended in a minimal example. I am still unsure of what is causing this issue but it is most definitely on my end. Thank you for your help!

**Comment by ivanpopelyshev** [comment]
field names tend to intersect in library-space and user-space. Check the names you use carefully
