### ISSUE TITLE
Quad Container

### ISSUE THREAD

**Issue by johnryb** [pixijs/pixi-projection#72]
I'm trying to control every corners of a container2d but having trouble doing that.

Pseudocode:
container.proj.mapQuad(new Rect(0, 0, 100, 100), [new Point(-40, -50), new Point(40, -50), new Point(50, 50), new Point(50, 50)]);

I'm trying to make it look like a trapezoid.

This is working when I use Sprite2s.

Pseudocode:
this.sprite.proj.mapBilinearSprite(this.sprite, this.anchoredPoints);

BTW, I'm using PIXI v4.0.

**Comment by ivanpopelyshev** [comment]
It should work. It works in https://pixijs.io/examples-v4/#/plugin-projection/quad-homo.js

Means you are doing something wrong in parts that I do not see, for example if that sprite is inside container and has position=(300,300)

**Comment by ivanpopelyshev** [comment]
Oh, wait, its Sprite2s... according to https://pixijs.io/examples-v4/#/plugin-projection/quad-bi.js you have to write `container.proj.mapBilinearSprite(sprite, quad);`  where container is Container2s and sprite is Sprite2s its child , or its the same element.

**Comment by johnryb** [comment]
> Oh, wait, its Sprite2s... according to https://pixijs.io/examples-v4/#/plugin-projection/quad-bi.js you have to write `container.proj.mapBilinearSprite(sprite, quad);` where container is Container2s and sprite is Sprite2s its child , or its the same element.

Sorry, I got you confused. My problem was not in Sprite2s but in container2d. My container has some sprites inside of it and I wanted to control each corners of the said container just like what I did on Sprite2s.

Note: I am using mapQuad method from container2d because it looks like the mapBilinearSprite from sprite2s. I might be using it incorrectly.

**Comment by ivanpopelyshev** [comment]
Yes, your code should work. Make sure all sprites are sprite2d

**Comment by johnryb** [comment]
Thanks for the clarification. I was using normal container inside container2d which is the problem.

PS. I am a silent reader of all your replies. You've been a great help Ivan since I started coding using PIXI.

**Comment by ivanpopelyshev** [comment]
Thank you!

Yes, all containers here are big hacks, they have special transform that holds matrix 3x3 or 4x4 instead of usual pixi 3x2. In container2s case its even worse. 

Placing regular container inside them works for small objects, but it loses the perspective part.

**Comment by nicolas-chaulet** [comment]
> Yes, your code should work. Make sure all sprites are sprite2d

This saved the day, it was not obvious to me. One can make sure all children are properly handled by calling `convertSubtreeTo2d`  on the parent container. Plugin is great by the way!
