### ISSUE TITLE
[Suggestion] put `dist` into `.gitignore` file

### ISSUE THREAD

**Issue by finscn** [pixijs/pixi-projection#8]

**Comment by ivanpopelyshev** [comment]
I dont have a way to distribute binaries independently. Same for other plugins. 

Not all people use npm.

**Comment by englercj** [comment]
> I dont have a way to distribute binaries independently. Same for other plugins.

You can upload built files on github releases ([for example](https://github.com/englercj/resource-loader/releases)).

**Comment by d3dc** [comment]
If you type:
```
npm install git+ssh://git@github.com/pixijs/pixi-projection.git\#branch
```

it will download the repo and read the `package.json` file:

```
 "main": "./dist/pixi-projection.js",
 "types": "./dist/pixi-projection.d.ts",
```

this wouldn't work if these files didn't exist.
