### ISSUE TITLE
Broken on v6-rc

### ISSUE THREAD

**Issue by arthuro555** [pixijs/pixi-projection#84]
When I try to load it on the production version of pixi v6-rc and v6-rc2, it crashes with the error `PIXI.systems.MaskSystem` is undefined.

**Comment by djmisterjon** [comment]
it seem work are you able to give a demo playground ?
![image](https://user-images.githubusercontent.com/24865815/104828342-602d6c80-5836-11eb-8f8e-668bfcf7d045.png)
Ivan will hate you if you tell him lies 🤣

My old demo seem work fine with V6.0.0-rc2 ! 
https://www.pixiplayground.com/#/edit/rlyWjgGjPbORymYpUC6o9

**Comment by djmisterjon** [comment]
oups you right !! cache problème on my breowser, after clear, demo not work . you true ! 
![image](https://user-images.githubusercontent.com/24865815/104828427-404a7880-5837-11eb-9316-5cd3084b2bff.png)
