### ISSUE TITLE
I am planning to change my game ui to isometric view, will I experience particle 2d render issue?

### ISSUE THREAD

**Issue by lancety** [pixijs/pixi-projection#89]
hi , I am really interested about making my top-down view game to isometric view, 
the game ui have sprites, spine characters, and surely I will use particles.  I am not planning to use any 3d feature in projection package, just wondering if particles in isometric view is possible or it is not supprted yet.
Thanks~~~

**Comment by ivanpopelyshev** [comment]
just isometric view should work fine. If you use any projection, well, i dont have particlecontainer that takes it into account )

**Comment by lancety** [comment]
It is just isometric, I am going to use the isometric demo approach,  scale stage to 0.6, rotate the inside child contaienr to PI/4, and make any children sprite's rotation to -PI/4  that need to be facing front.  

If particles append to the sprite, it should follow sprite's rotation I guess. 

Thank you Ivan~

**Comment by ivanpopelyshev** [comment]
Oh, then it shouldn't be a problem , its usual 2d transform 3x2 matrix that is used in ParticleContainer
