### ISSUE TITLE
TilingSprite works in isometric mode but not in perspective mode

### ISSUE THREAD

**Issue by paganaye** [pixijs/pixi-projection#94]
I took your simple `One-point with return to affine` and modified it to display an issue with TilingSprite2d.
Sample code with is here:
https://codepen.io/paganaye/pen/abwZeam?editors=1010

As you can see in the example I have a Sprite2d and a TilingSprite2d and they don't behave the same way.
The purple part displays fine in isometric mode but not perspective mode (it looks like it only support isometric mode).

I'd be happy to contribute. I had a look but it is above my level
It looks like in Sprite2d you do a lot of calculations depending on whether we're in affine mode or not.
In tiling sprite it doesn't seem to be the case.

**Comment by ivanpopelyshev** [comment]
Yep, that's a bug. I forgot to copy calculateVertices stuff most probably

**Comment by ivanpopelyshev** [comment]
Oh, wait, it doesnt need calculateVertices at all

**Comment by ivanpopelyshev** [comment]
loool. I use `ts.transform.worldTransform.toArray(true)` and not overriden `ts.worldTransform`

**Comment by ivanpopelyshev** [comment]
OK. https://cdn.jsdelivr.net/npm/pixi-projection@latest/dist/pixi-projection.umd.js , version 0.4.3

it works! thank you for the notice. Here is a patch: https://github.com/pixijs/pixi-projection/commit/8502b16b2aa7df421f8dd66182e9dd4a9612e923

**Comment by paganaye** [comment]
Bug is fixed. Excellent.
https://codepen.io/paganaye/pen/abwmmqd?editors=1010
