### ISSUE TITLE
Bunnies in the sky

### ISSUE THREAD

**Issue by paganaye** [pixijs/pixi-projection#95]
I took your simple One-point with return to affine and modified it to display an issue with TilingSprite2d.
Sample code with is here:
https://codepen.io/paganaye/pen/YzQGGWN?editors=1010

Here we befriend bunny with 20 friends. There are all following him and should look in a row. Some however appear in the sky when in fact they should be behind the camera. What should I do to make those not appear?

**Comment by ivanpopelyshev** [comment]
There's no culling for 2d case, its your job to do it.  2d is very limited, but its easy. I think this is the only lib that can use it.

There's some culling for 3d, but i dont remember whether i made TilingSprite for it, most probably TilingSprite2d should work there too

**Comment by paganaye** [comment]
I made a branch that uses a Camera3d and Sprite3d.
It works well. This is more understandable to me than the setAxisY method.
The TilingSprite2d crashes there though. 
I just used 256 sprites and it works wel.
I will close this issue. If you want me to create a new one about the TilingSprite3d, I would be happy to do it.

**Comment by ivanpopelyshev** [comment]
yes, need a new one for TilingSprite3d
